projects:
  doggie:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: wc6e5w44vvfrpozvfbejzhbtxu
      endpoints:
        prod: >-
          https://g3k4dxf77nem7oe4cxgddxfzdy.appsync-api.us-west-2.amazonaws.com/graphql
